Parser-InToHyLo: SyntacticAnalyser Class Reference
SyntacticAnalyser Class Reference
This class will perform a Shift and Reduce on our input Formula.
#include <SyntacticAnalysis.h>
Public Member Functions
SyntacticAnalyser (const char *file)
Constructor of the Syntactic Analyser.
~SyntacticAnalyser ()
Destructor of the SyntaxticAnalyser.
void parseFormula (vector< Formula * > &formulas)
Parse the file (saved in lx) to extract the formula.
Formula * getFormula ()
This function return the parsed formula.
void prepareParser ()
this function will clean the 2 stacks (token and formula elements)
void pushUnary (int tk, int id=0)
This function will push an unary element.
void pushNull (int tk)
This function will push a NULL token.
void merge (int v1, int v2, int v3)
This function will merge the stacks.
bool reduce ()
Combine elements on the stack.
Private Attributes
LexicalAnalyser * lx
The Lexical Analyser of our Formula.
vector< Formula * > stackFormula
By using Shift and Reduce, we will stack every element of our Formula.
vector< int > stackToken
By using Shift and Reduce, we will stack every token.
Detailed Description
This class will perform a Shift and Reduce on our input Formula.
Definition at line 37 of file SyntacticAnalysis.h.
Constructor & Destructor Documentation
SyntacticAnalyser::SyntacticAnalyser (const char * file) inline
Constructor of the Syntactic Analyser.
It will call the LexicalAnalyser on the input file in parameter
Parameters
[in] file the filename of our input formula in InToHyLo
Definition at line 49 of file SyntacticAnalysis.h.
 { lx = new LexicalAnalyser(file); }
SyntacticAnalyser::~SyntacticAnalyser () inline
Destructor of the SyntaxticAnalyser.
Definition at line 52 of file SyntacticAnalysis.h.
 { delete lx; }
Member Function Documentation
Formula* SyntacticAnalyser::getFormula () inline
This function return the parsed formula.
Returns
the parsed formula
Definition at line 66 of file SyntacticAnalysis.h.
Referenced by parseFormula().
     {
       assert(stackToken.size() == 1);
       assert(stackFormula.size() == 1);
       Formula *ret = stackFormula[0];
       prepareParser();
       return ret;
     }
void SyntacticAnalyser::merge (int v1, int v2, int v3) inline
This function will merge the stacks.
Parameters
[in] v1 should be stackToken[size()-3]
[in] v2 should be stackToken[size()-2]
[in] v3 should be stackToken[size()-1]
Definition at line 146 of file SyntacticAnalysis.h.
Referenced by reduce().
     {
       unsigned int size = stackToken.size();
       assert(size > 2);
       assert(stackToken[size - 3] == v1);
       assert(stackToken[size - 2] == v2);
       assert(stackToken[size - 1] == v3);
       stackFormula[stackFormula.size() - 3] = stackFormula[stackFormula.size() - 2];
       stackFormula.pop_back();
       stackFormula.pop_back();
       stackToken[stackToken.size() - 3] = stackToken[stackToken.size() - 2];
       stackToken.pop_back();
       stackToken.pop_back();
       assert(stackToken.size() == stackFormula.size());
     }
void SyntacticAnalyser::parseFormula (vector< Formula * > & formulas)
Parse the file (saved in lx) to extract the formula.
Parameters
[out] formulas the formula that we extracted from the parsed file.
Definition at line 31 of file SyntacticAnalysis.cc.
References AND, BEGIN, BOX, COMMENT, LexicalAnalyser::currentValue, DIAMOND, LexicalAnalyser::eatLine(), END, END_FILE, EQUIV, FALSE, FORMULA, getFormula(), IMPLY, lx, LexicalAnalyser::nextToken(), NOT, OR, PAR_LEFT, PAR_RIGHT, prepareParser(), PROPOSITIONAL, pushNull(), pushUnary(), reduce(), stackFormula, stackToken, and TRUE.
Referenced by main().
 {
   prepareParser();
   int tk = lx->nextToken(), id = lx->currentValue;
   while(tk != END_FILE)
     {
       while(tk == COMMENT){lx->eatLine(); tk = lx->nextToken(); id = lx->currentValue;}
       if(tk == PROPOSITIONAL || tk == TRUE || tk == FALSE) // simple formula
         {
           switch(tk)
             {
             case PROPOSITIONAL : stackFormula.push_back(new PropositionalVariable(id)); break;
             case TRUE : stackFormula.push_back(new Top()); break;
             case FALSE : stackFormula.push_back(new Bottom()); break;
             }
           stackToken.push_back(FORMULA);
         }
       else if(tk == PAR_LEFT || tk == BEGIN || tk == PAR_RIGHT || tk == END) pushNull(tk);
       else if(tk == BOX || tk == DIAMOND) pushUnary(tk, id);
       else if(tk == NOT || tk == IMPLY || tk == EQUIV || tk == OR || tk == AND) pushUnary(tk);
       while(tk != COMMENT && reduce());
       if(tk == END) formulas.push_back(getFormula());
       tk = lx->nextToken();
       id = lx->currentValue;
     }
 } // parseFormula
void SyntacticAnalyser::prepareParser () inline
this function will clean the 2 stacks (token and formula elements)
Definition at line 79 of file SyntacticAnalysis.h.
Referenced by parseFormula().
     {
       stackToken.clear();
       stackFormula.clear();
     }
void SyntacticAnalyser::pushNull (int tk) inline
This function will push a NULL token.
Parameters
[in] tk our token.
Definition at line 131 of file SyntacticAnalysis.h.
Referenced by parseFormula().
     {
       stackFormula.push_back(NULL);
       stackToken.push_back(tk);
     } // pushNull
void SyntacticAnalyser::pushUnary (int tk, int id = 0) inline
This function will push an unary element.
Parameters
[in] tk our token. It can be a {Box,Diamond,Not,Imply,Equiv,Or,And}
[in] id the agent ID in case of Box and Diamond.
Definition at line 92 of file SyntacticAnalysis.h.
References AND, BOX, DIAMOND, EQUIV, IMPLY, NOT, and OR.
Referenced by parseFormula().
     {
       Formula *f = NULL;
       switch(tk) {
         case BOX:
           f = new Box(id);
           break;
         case DIAMOND:
           f = new Diamond(id);
           break;
         case NOT:
           f = new Neg();
           break;
         case IMPLY:
           f = new Imply();
           break;
         case EQUIV:
           f = new Equiv();
           break;
         case OR:
           f = new Or();
           break;
         case AND:
           f = new And();
           break;
       }
       stackToken.push_back(tk);
       stackFormula.push_back(f);
       assert(f);
     } // pushUnary
bool SyntacticAnalyser::reduce () inline
Combine elements on the stack.
Returns
true if everything is ok, false otherwise.
Definition at line 68 of file SyntacticAnalysis.cc.
References AND, BEGIN, BOX, DIAMOND, END, EQUIV, FORMULA, IMPLY, merge(), NOT, OR, PAR_LEFT, PAR_RIGHT, stackFormula, and stackToken.
Referenced by parseFormula().
 {
   if(stackToken.size() < 3) return false;
   // we always have BEGIN as first element
   assert(stackToken[0] == BEGIN);
   assert(stackToken.size() == stackFormula.size());
   int last = stackToken.size() - 1;
   if(stackToken[last] == FORMULA)
     {
       switch(stackToken[last - 1])
         {
         case BOX :
         case DIAMOND :
         case NOT :
           stackFormula[last - 1]->addChild(stackFormula[last]);
           stackToken[last - 1] = FORMULA;
           stackFormula.pop_back(); stackToken.pop_back();
           assert(stackToken.size() == stackFormula.size());
           return true;
         }
     }
   else if(stackToken[last] == PAR_RIGHT || stackToken[last] == END)
     {
       if(stackToken[last - 1] == FORMULA && stackToken[last - 2] == PAR_LEFT) merge(PAR_LEFT, FORMULA, PAR_RIGHT);
       else if(stackToken[last - 1] == FORMULA && stackToken[last - 2] == BEGIN) merge(BEGIN, FORMULA, END);
       else
         {
           assert(stackToken.size() > 4);
           assert(stackToken[last - 1] == FORMULA && stackToken[last - 3] == FORMULA);
           stackFormula[last - 2]->addChild(stackFormula[last - 3]);
           stackFormula[last - 2]->addChild(stackFormula[last - 1]);
           stackFormula[last - 3] = stackFormula[last - 2];
           stackFormula[last - 2] = stackFormula[last];
           stackToken[last - 3] = FORMULA;
           stackToken[last - 2] = stackToken[last];
           stackFormula.pop_back(); stackFormula.pop_back();
           stackToken.pop_back(); stackToken.pop_back();
         }
       assert(stackToken.size() == stackFormula.size());
       return true;
     }
   else if(stackToken[last] == AND || stackToken[last] == OR || stackToken[last] == IMPLY || stackToken[last] == EQUIV)
     {
       if(stackToken[last - 2] == AND || stackToken[last - 2] == OR || stackToken[last - 2] == IMPLY || stackToken[last - 2] == EQUIV)
         {
           if(stackFormula[last]->priority <= stackFormula[last - 2]->priority)
             {
               assert(stackFormula.size() > 4);
               stackFormula[last - 2]->addChild(stackFormula[last - 3]);
               stackFormula[last - 2]->addChild(stackFormula[last - 1]);
               stackFormula[last - 3] = stackFormula[last - 2];
               stackFormula[last - 2] = stackFormula[last];
               stackToken[last - 3] = FORMULA;
               stackToken[last - 2] = stackToken[last];
               stackFormula.pop_back(); stackFormula.pop_back();
               stackToken.pop_back(); stackToken.pop_back();
               assert(stackToken.size() == stackFormula.size());
               return true;
             }
         }
     }
   assert(stackToken.size() == stackFormula.size());
   return false;
 } // reduce
Field Documentation
LexicalAnalyser* SyntacticAnalyser::lx private
The Lexical Analyser of our Formula.
Definition at line 177 of file SyntacticAnalysis.h.
Referenced by parseFormula().
vector<Formula *> SyntacticAnalyser::stackFormula private
By using Shift and Reduce, we will stack every element of our Formula.
Definition at line 180 of file SyntacticAnalysis.h.
Referenced by parseFormula(), and reduce().
vector<int> SyntacticAnalyser::stackToken private
By using Shift and Reduce, we will stack every token.
Definition at line 183 of file SyntacticAnalysis.h.
Referenced by parseFormula(), and reduce().
The documentation for this class was generated from the following files:
SyntacticAnalysis.h
SyntacticAnalysis.cc