Parser-InToHyLo: Main.cc File Reference
Main.cc File Reference
#include <algorithm>
#include <sys/types.h>
#include <sys/wait.h>
#include "SyntacticAnalysis.h"
Functions
void help (char *arg0)
This function will display a help message to explain the user how to use the solver.
void displayFormulas (vector< Formula * > &formulas)
int main (int argc, char **argv)
Function Documentation
void displayFormulas (vector< Formula * > & formulas) inline
Definition at line 66 of file Main.cc.
Referenced by main().
 {
   for(const auto & formula : formulas)
   {
     formula->display(stdout);
     std::cout << std::endl;
   }
 } // displayFormulas
void help (char * arg0) inline
This function will display a help message to explain the user how to use the solver.
Parameters
[in] arg0 the name of the program (which is the argv[0] in the main.
Definition at line 36 of file Main.cc.
Referenced by main().
 {
   std::cout << "c ------------------------------------------------------------------------------------------------------------------------------------------------" << std::endl;
   std::cout << "c " << std::endl;
   std::cout << "c Execute as follow: " << arg0 << " ./path-to-InToHyLo formula"                                                                                     << std::endl;
   std::cout << "c " << std::endl;
   std::cout << "c ------------------------------------------------------------------------------------------------------------------------------------------------" << std::endl;
   std::cout << "c This file may contain multiple intohylo formula, all embedded between 'begin' and 'end'. "                                                        << std::endl;
   std::cout << "c An InToHyLo formula is constructed recursively as follow: "                                                                   << std::endl << "c" << std::endl;
   std::cout << "c\t $file$ ::= begin $formula$ end "          << std::endl << "c" << std::endl;
   std::cout << "c\t $formula$ ::= ( $formula$ ) "           << std::endl;
   std::cout << "c\t      |    ::= true"                     << std::endl;
   std::cout << "c\t      |    ::= false"                    << std::endl;
   std::cout << "c\t      |    ::= p$id$"                    << std::endl;
   std::cout << "c\t      |    ::= ~$formula$"               << std::endl;
   std::cout << "c\t      |    ::= [r$id$] $formula$ "       << std::endl;
   std::cout << "c\t      |    ::= <r$id$> $formula$ "       << std::endl;
   std::cout << "c\t      |    ::= $formula$ & $formula$"    << std::endl;
   std::cout << "c\t      |    ::= $formula$ | $formula$"    << std::endl;
   std::cout << "c\t      |    ::= $formula$ -> $formula$"   << std::endl;
   std::cout << "c\t      |    ::= $formula$ <-> $formula$"  << std::endl;
   std::cout << "c" << std::endl;
   std::cout << "c\t Where identifiers $id$ are numerical sequences. "                                                                                                 << std::endl;
   std::cout << "c ================================================================================================================================================" << std::endl;
   exit(1);
 } // help
int main (int argc, char ** argv)
This function is the main entrance of the program.
Parameters
[in] argc the number of arguments for the main.
[in] argv all the arguments of the main in a format char*.
Returns
0 if everything went as expected, something else otherwise.
Definition at line 86 of file Main.cc.
References displayFormulas(), help(), and SyntacticAnalyser::parseFormula().
 {
   vector<Formula *> formulas;
   setbuf(stdout, NULL);
   if(argc <= 1) help(argv[0]);
   SyntacticAnalyser sx(argv[1]);
   sx.parseFormula(formulas);
   displayFormulas(formulas);
   formulas.clear();
   return 0;
 } // main