Parser-InToHyLo: LexicalAnalyser Class Reference
LexicalAnalyser Class Reference
This class represents the lexical analysis of the InToHyLo format.
#include <LexicalAnalysis.h>
Public Member Functions
LexicalAnalyser (const char *fileName)
Constructor of the LexicalAnalyser.
LexicalAnalyser ()
Default constructor, cin equals NULL after.
~LexicalAnalyser ()
Destructor of the LexicalAnalyser.
int nextToken ()
Read the flux and return the next token. The value is also save.
void keepToken (int tk, int id)
This function will keep the token in the savedToken stack.
string tokenToChar (int tk)
This function will transform a token into a string.
int parseInt ()
Read a number from cin.
void eatLine ()
Consum the current line.
Data Fields
int currentValue
the current value during the lexical analysis
char currentChar [MAX_SIZE]
the current string during the lexical analysis
FILE * cin
a reference to the file that we are reading
Private Member Functions
bool checkWord (string s, int start)
This function check if the word s starts at the position 'start'.
Private Attributes
vector< int > savedToken
vector< int > savedId
Detailed Description
This class represents the lexical analysis of the InToHyLo format.
Definition at line 60 of file LexicalAnalysis.h.
Constructor & Destructor Documentation
LexicalAnalyser::LexicalAnalyser (const char * fileName) inline
Constructor of the LexicalAnalyser.
This function will just open the file with the filename
Parameters
[in] fileName the file that we want to open
Definition at line 82 of file LexicalAnalysis.h.
 { cin = fopen(fileName, "r"); }
LexicalAnalyser::LexicalAnalyser () inline
Default constructor, cin equals NULL after.
Definition at line 87 of file LexicalAnalysis.h.
 { cin = NULL; }
LexicalAnalyser::~LexicalAnalyser () inline
Destructor of the LexicalAnalyser.
This function will just close cin if it is still open.
Definition at line 94 of file LexicalAnalysis.h.
 { if(cin) fclose(cin); }
Member Function Documentation
bool LexicalAnalyser::checkWord (string s, int start) private
This function check if the word s starts at the position 'start'.
Parameters
[in] s the word that we are checking
[in] start the index of the first character.
Returns
true if the word starts, false otherwise.
Definition at line 109 of file LexicalAnalysis.cc.
References cin.
Referenced by nextToken().
 {
   for(unsigned int i = start ; i<s.size() ; i++)
     {
       int c = getc(cin);
       if(c != s[i] && c != (s[i] - 'a' + 'A') && c != (s[i] - 'A' + 'a')) return false;
     }
   return true;
 } // checkWord
void LexicalAnalyser::eatLine () inline
Consum the current line.
Definition at line 179 of file LexicalAnalysis.h.
Referenced by SyntacticAnalyser::parseFormula().
     {
       int c = getc(cin);
       while(c != '\n' && c != EOF) c = getc(cin);
     } // eatLine
void LexicalAnalyser::keepToken (int tk, int id) inline
This function will keep the token in the savedToken stack.
Parameters
[in] tk the token that we want to save
[in] id the id that we want to save.
Definition at line 111 of file LexicalAnalysis.h.
References savedId, and savedToken.
     {
       savedToken.push_back(tk);
       savedId.push_back(id);
     } // keepToken
int LexicalAnalyser::nextToken ()
Read the flux and return the next token. The value is also save.
Returns
the next token.
Definition at line 32 of file LexicalAnalysis.cc.
References AND, BEGIN, BOX, checkWord(), cin, COMMENT, currentValue, DIAMOND, END, END_FILE, EQUIV, ERROR, FALSE, IMPLY, NOT, OR, PAR_LEFT, PAR_RIGHT, parseInt(), PROPOSITIONAL, RELATION, savedId, savedToken, and TRUE.
Referenced by SyntacticAnalyser::parseFormula().
 {
   if(savedToken.size())
     {
       int ret = savedToken.back();
       savedToken.pop_back();
       currentValue = savedId.back();
       savedId.pop_back();
       return ret;
     }
   if(cin == NULL)
   {
     std::cerr << "c Problem with the file: Not existing or not enough rights to open it... " << std::endl;
     std::cerr << "c The solver will not abort its execution..." << std::endl;
     exit(-1);
   }
   int c = getc(cin);
   while(c == ' ' || c == '\t' || c == '\n') c = getc(cin);
   if(c == '#') return COMMENT;
   else if(c == '<')
     {
       c = getc(cin);
       switch(c)
         {
         case '-' : c = getc(cin);             if(c == '>') return EQUIV;   else break;
         case 'r' : parseInt(); c = getc(cin); if(c == '>') return DIAMOND; else break;
         }
     }
   else if(c == '-')
     {
       c = getc(cin);
       if(c == '>') return IMPLY;
     }
   else if(c == '[')
     {
       c = getc(cin);
       if(c == 'r') { parseInt(); c = getc(cin); if(c == ']') return BOX; }
     }
   else if(c == '&') return AND;
   else if(c == '|') return OR;
   else if(c == '~') return NOT;
   else if(c == '(') return PAR_LEFT;
   else if(c == ')') return PAR_RIGHT;
   else if(c == 't' || c == 'T') return checkWord("true", 1) ? TRUE : ERROR;
   else if(c == 'f' || c == 'F') return checkWord("false", 1) ? FALSE : ERROR;
   else if(c == 'b' || c == 'B') return checkWord("begin", 1) ? BEGIN : ERROR;
   else if(c == 'e' || c == 'E') return checkWord("end", 1) ? END : ERROR;
   else if(c == 'r' || c == 'R') return RELATION;
   else if(c == 'p' || c == 'P')
     {
       parseInt();
       return PROPOSITIONAL;
     }
   else if(c == EOF) return END_FILE;
   std::cerr << "c Error Lexical Analysis: the character " << (char) c << " is unknown" << std::endl;
   exit(2);
 } // nextToken
int LexicalAnalyser::parseInt () inline
Read a number from cin.
Returns
the number read.
Definition at line 159 of file LexicalAnalysis.h.
References currentValue.
Referenced by nextToken().
     {
       currentValue = 0;
       int c = getc(cin);
       assert(c >= '0' && c <= '9');
       while(c != EOF && (c >= '0' && c <= '9'))
         {
           currentValue = currentValue * 10 + (c - '0');
           c = getc(cin);
         }
       fseek(cin , -1, SEEK_CUR);
       return currentValue;
     } // parseInt
string LexicalAnalyser::tokenToChar (int tk) inline
This function will transform a token into a string.
Parameters
[in] tk the token from which we want the string equivalent
Returns
the string equivalent of the parameter
Definition at line 125 of file LexicalAnalysis.h.
References AND, BEGIN, BOX, COMMENT, DIAMOND, END, END_FILE, EQUIV, ERROR, FALSE, FORMULA, IMPLY, NOT, NUMBER, OR, PAR_LEFT, PAR_RIGHT, PROPOSITIONAL, RELATION, and TRUE.
     {
       switch(tk)
         {
           case TRUE          : return "TRUE";
           case FALSE         : return "FALSE";
           case END_FILE      : return "END_FILE";
           case BEGIN         : return "BEGIN";
           case END           : return "END";
           case ERROR         : return "ERROR";
           case RELATION      : return "RELATION";
           case PROPOSITIONAL : return "PROPOSITIONAL";
           case NUMBER        : return "NUMBER";
           case OR            : return "OR";
           case AND           : return "AND";
           case PAR_LEFT      : return "PAR_LEFT";
           case PAR_RIGHT     : return "PAR_RIGHT";
           case NOT           : return "NOT";
           case COMMENT       : return "COMMENT";
           case IMPLY         : return "->";
           case EQUIV         : return "<->";
           case BOX           : return "[]";
           case DIAMOND       : return "<>";
           case FORMULA       : return "FORMULA";
           default            : return "UNKNOW";
         }
     } // tokenToChar
Field Documentation
FILE* LexicalAnalyser::cin
a reference to the file that we are reading
Definition at line 72 of file LexicalAnalysis.h.
Referenced by checkWord(), and nextToken().
char LexicalAnalyser::currentChar[MAX_SIZE]
the current string during the lexical analysis
Definition at line 69 of file LexicalAnalysis.h.
int LexicalAnalyser::currentValue
the current value during the lexical analysis
Definition at line 66 of file LexicalAnalysis.h.
Referenced by nextToken(), SyntacticAnalyser::parseFormula(), and parseInt().
vector<int> LexicalAnalyser::savedId private
Definition at line 200 of file LexicalAnalysis.h.
Referenced by keepToken(), and nextToken().
vector<int> LexicalAnalyser::savedToken private
Definition at line 199 of file LexicalAnalysis.h.
Referenced by keepToken(), and nextToken().
The documentation for this class was generated from the following files:
LexicalAnalysis.h
LexicalAnalysis.cc